### ISSUE TITLE
Dependencies conflict for python server

### ISSUE THREAD

**Issue by yegorLitvinov** [stripe-samples/card-brand-choice#11]
# Bug report

## Describe the bug

```
ERROR: Cannot install -r requirements.txt (line 10) and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.22.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

```

## To Reproduce

```
pip install -r requirements.txt
```

## Expected behavior

Successfully installed dependencies

## System information

- OS: macOS
- Server environment `Python 3.10.4`

**Comment by charliegerard-stripe** [comment]
Hey @yegorLitvinov! 👋 

Thanks for opening this issue! I worked on a fix (#13) and just merged the PR so I'm going to close this issue 🙂
